name: ItemFilter
version: ${project.version}
main: com.pustinek.itemfilter.ItemFilter
api-version: 1.14
authors: [Pustinek]
description: Minecraft item filter plugin
commands:
  itemfilter:
    description: 'for all the commands use /ItemFilter help'
    usage: '/command'
    aliases: [filter, if]
  permissions:
    itemfilter.help:
      description: Show plugin help
      default: false
    itemfilter.*:
      description: 'Give access to all commands of itemfilter'
      default: op
      children:
        itemfilter.use: true
        itemfilter.restart: true
        itemfilter.help: true
    itemfilter.use:
      description: Basic usage of the plugin
      default: false
    itemfilter.reload:
      description: Reload the plugin
      default: op
